apiVersion: v1
kind: Secret
data:
  username: cG9zdGdyZXM=
  password: dGVzdHBhc3N3b3Jk
metadata:
  labels:
    app.kubernetes.io/name: keycloak-operator
    app.kubernetes.io/version: 23.0.6
    app.kubernetes.io/managed-by: quarkus
  name: keycloak-db-secret
type: Opaque
