---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: keycloak-tls-certificates
spec:
  acme:
    email: rabota.abn@gmail.com
    privateKeySecretRef:
      name: letsencrypt
    server: https://acme-v02.api.letsencrypt.org/directory
    solvers:
    - http01:
        ingress:
            class: nginx
