apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secrets
type: Opaque
stringData:
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
  PROXY_ADDRESS_FORWARDING: "true"
  KEYCLOAK_HEALTH_ENABLED: "true"
  KEYCLOAK_HTTP_ENABLED: "true"
  KEYCLOAK_HOSTNAME_URL: "https://keycloak.infra.tbhub.ru/"
  KEYCLOAK_HOSTNAME_ADMIN_URL: "https://keycloak.infra.tbhub.ru/auth"
  KEYCLOAK_USER: "admin"
  KEYCLOAK_PASSWORD: "lL02cE0FQ0ojtBVJ6VybDr9"
  KEYCLOACK_PROXY: "edge"
  QUARKUS_THREAD_POOL_MAX_THREADS: "66"
  JAVA_OPTS_APPEND: >
    -Xms512m -Xmx1524m -Djgroups.thread_dumps_threshold=1
